config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :index, :show]
  resources :sessions, only: [:create]
  get '/signout' , to: 'sessions#signout'
  get '/signin' , to: 'sessions#new'
  resources :groups, only: [:new, :create, :index, :show]
  resources :recipes, only: [:new, :create, :index, :show]
  get '/search', to: 'recipes#search'
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :icon, presence: true
  validates_format_of :icon, with: /\.(png|jpg|jpeg)\z/i, message: ': false link, imgur.com is recommended'
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :video, presence: true, uniqueness: true
  validates :ingredients, presence: true
  validates :amount, presence: true, uniqueness: false
  validates :author_id, presence: true
  validates :group_id, presence: true
  # rubocop:disable Layout/LineLength
  validates_format_of :video, with: %r{\A(http(s)?:\/\/)?((w){3}.)?youtu(be|.be)?(\.com)?\/.+\z}i, message: 'should be a YouTube Video Link'
  # rubocop:enable Layout/LineLength
  belongs_to :author, class_name: 'User'
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :recipes, foreign_key: :author_id, dependent: :destroy
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged?
  before_action :set_user
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @recipes = Recipe.where({ group_id: params[:id] }).includes([:author])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # rubocop:disable Style/GuardClause
  def logged?
    if cookies[:id] == '' || cookies[:id].nil?
      flash[:danger] = 'Please log in.'
      redirect_to signin_path
    end
  end
  # rubocop:enable Style/GuardClause

  def set_user
    @current_user = User.find(cookies[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged?
  before_action :set_user
  def index
    @recipes = Recipe.all.includes([:author])
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def search
    search = params[:search]
    @recipes = Recipe.where('name LIKE ? OR ingredients LIKE ?', "%#{search}%", "%#{search}%").includes([:author])
  end

  def new
    @recipe = User.first.recipes.new
  end

  def create
    @recipe = @current_user.recipes.new(user_params)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # rubocop:disable Style/GuardClause
  def logged?
    if cookies[:id] == '' || cookies[:id].nil?
      flash[:danger] = 'Please log in.'
      redirect_to signin_path
    end
  end
  # rubocop:enable Style/GuardClause

  def set_user
    @current_user = User.find(cookies[:id])
  end

  def user_params
    params.require(:recipe).permit(:name, :group_id, :amount, :video, :ingredients)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_user
  before_action :logged?, only: %i[new create]
  def new; end

  def create
    if User.where(name: params[:name]).exists?
      cookies[:id] = User.where(name: params[:name]).first.id
      redirect_to users_path
    else
      flash[:danger] = 'User doesn\'t exist!'
      redirect_to signin_path
    end
  end

  def signout
    cookies[:id] = ''
    redirect_to signin_path
  end

  private

  # rubocop:disable Style/GuardClause
  def logged?
    if cookies[:id].to_i.positive?
      flash[:success] = 'You\'re Logged In!'
      redirect_to users_path
    end
  end

  # rubocop:enable Style/GuardClause
  def set_user
    @current_user = 'guest'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged?, except: %i[new create]
  before_action :set_user, except: %i[new create]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recipes = Recipe.where({ author_id: params[:id] })
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # rubocop:disable Style/GuardClause
  def logged?
    if cookies[:id] == '' || cookies[:id].nil?
      flash[:danger] = 'Please log in.'
      redirect_to signin_path
    end
  end
  # rubocop:enable Style/GuardClause

  def set_user
    @current_user = User.find(cookies[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_youtube_id(url)
    id = ''
    url = url.gsub(/(>|<)/i, '').split(%r{(vi/|v=|/v/|youtu\.be/|/embed/)})
    if !url[2].nil?
      id = url[2].split(/[^0-9a-z_\-]/i)
      id = id[0]
    else
      id = url
    end
    id
  end
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<% @groups.each do |u| %>
<div class="groups-container">
<a href="<%=groups_path + "/" + u.id.to_s%>"><%= u.name %></a>
<img src="<%=u.icon%>" alt="<%= u.name%>">
</div>
<% end %>

app/views/groups/new.html.erb
<div class="form-div">
<%= form_for @group do |f|%>
<% if @group.errors.any? %> <div id="error_explanation"> <h2><%= pluralize(@group.errors.count, "error") %> prohibited this post from being saved:</h2> <ul> <% @group.errors.full_messages.each do |msg| %> <li><%= msg %></li> <% end %> </ul> </div> <% end %> 
<label for="name">group name</label>
<%= f.text_field :name%>
<label for="icon">icon link</label>
<%= f.text_field :icon%>
<%= f.submit "Submit"%>
<br>
<%end%>
</div>

app/views/groups/show.html.erb
<div class="groups-container">
<p><%= @group.name %></p>
<img src="<%= @group.icon %>" alt="<%= @group.name %>">
</div>
<% @recipes.each do |r|%>
<div class="recipe-container">
<p class="name"><a class="n-link" href="<%= recipes_path + "/" + r.id.to_s%>"><%= r.name %></a> By <a href="<%= users_path + "/" + r.author.id.to_s%>"><%= r.author.name%></a></p>
<p>Ingredients: </p>
<div class="ingredients"> <%= simple_format(r.ingredients).html_safe%></div>
<p> How To Video: </p>
<iframe class="embed" src="https://www.youtube.com/embed/<%= get_youtube_id(r.video) %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p>amount: <%= r.amount %></p>
<a class="view-link" href="<%= recipes_path + "/" + r.id.to_s%>">View</a>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Katchy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if cookies[:id].to_i.positive? %>
  <nav id="nav">
  <hr>
  <%= form_tag search_path, :method => 'get', :class => 'search_form' do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: "enter a search here" %>
    <%= submit_tag '🔍', :name => nil %>
  </p>
<% end %>
  <hr>
  <p class="user-tab">Hello, <a href="<%= users_path + "/" + @current_user.id.to_s %>"><%= @current_user.name %></a> - <a href="<%= signout_path %>" class="logout">Logout!</a></p>
  <hr>
  <a href="<%= users_path %>">All Users</a>
  <hr>
  <a href="<%= groups_path %>">All Groups</a>
  <hr>
  <a href="<%= recipes_path %>">All Recipes</a>
  <hr>
  <button id="menu-btn" onclick="hamburgerBtn()">	&#9776;</button>
  </nav>
  <% end %>
    <main>
    <% if flash[:danger] || flash[:success] %>
 <div class="flash-container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
    </div>
    <% end %>
  </div>
  <% end %>
    <%= yield %>

    <div id="new">
    <button id="new-btn"><svg id="new-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M24 10h-10v-10h-4v10h-10v4h10v10h4v-10h10z" /></svg></button>
  <% if cookies[:id].to_i.positive? %>
    <a class="add" id="add-group" href="<%= new_group_path %>">New Group</a>
    <a class="add" id="add-recipe" href="<%= new_recipe_path %>">New Recipe</a>
    <% else %>
    <a class="add" id="add-group" href="<%= new_user_path %>">New User</a>
    <% end %>
    </div>
    </main>
  </body>
</html>

app/views/recipes/index.html.erb
<% @recipes.each do |r|%>
<div class="recipe-container">
<p class="name"><a class="n-link" href="<%= recipes_path + "/" + r.id.to_s%>"><%= r.name %></a> By <a href="<%= users_path + "/" + r.author.id.to_s%>"><%= r.author.name%></a></p>
<p>Ingredients: </p>
<div class="ingredients"> <%= simple_format(r.ingredients).html_safe%></div>
<p> How To Video: </p>
<iframe class="embed" src="https://www.youtube.com/embed/<%= get_youtube_id(r.video) %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p>amount: <%= r.amount %></p>
<a class="view-link" href="<%= recipes_path + "/" + r.id.to_s%>">View</a>
</div>
<%end%>

app/views/recipes/new.html.erb
<div class="form-div">
<%= form_for @recipe do |f|%>
<% if @recipe.errors.any? %> <div id="error_explanation"> <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this post from being saved:</h2> <ul> <% @recipe.errors.full_messages.each do |msg| %> <li><%= msg %></li> <% end %> </ul> </div> <% end %> 
<label for="name">Recipe name</label>
<%= f.text_field :name%>
<br>
<label for="group_id">Group name</label>
<%= f.collection_select :group_id, Group.order(:name),:id,:name, include_blank: true %>
<br>
<label for="ingredients">Recipe Ingredients (each in a line)</label>
<%= f.text_area :ingredients%>
<br>
<label for="video">video link</label>
<%= f.text_field :video %>
<br>
<label for="amount">amount (in minutes)</label>
<%= f.number_field :amount%>
<br>
<%= f.submit "Submit"%>
<%end%>
</div>

app/views/recipes/search.html.erb
<% @recipes.each do |r|%>
<div class="recipe-container">
<p class="name"><a class="n-link" href="<%= recipes_path + "/" + r.id.to_s%>"><%= r.name %></a> By <a href="<%= users_path + "/" + r.author.id.to_s%>"><%= r.author.name%></a></p>
<p>Ingredients: </p>
<div class="ingredients"> <%= simple_format(r.ingredients).html_safe%></div>
<p> How To Video: </p>
<iframe class="embed" src="https://www.youtube.com/embed/<%= get_youtube_id(r.video) %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p>amount: <%= r.amount %></p>
<a class="view-link" href="<%= recipes_path + "/" + r.id.to_s%>">View</a>
</div>
<%end%>

app/views/recipes/show.html.erb
<div class="recipe-container" style="border: none;">
<p class="name"><a class="n-link" href="<%= recipes_path + "/" + @recipe.id.to_s%>"><%= @recipe.name %></a> By <a href="<%= users_path + "/" + @recipe.author.id.to_s%>"><%= @recipe.author.name%></a></p>
<p>Ingredients: </p>
<div class="ingredients no-overflow"> <%= simple_format(@recipe.ingredients).html_safe%></div>
<p> How To Video: </p>
<iframe class="embed high-vid" src="https://www.youtube.com/embed/<%= get_youtube_id(@recipe.video) %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p>amount: <%= @recipe.amount %></p>
</div>

app/views/users/index.html.erb
<div id="users-container">
<% @users.each do |u| %>
<div class="users">
<p><%= u.name %></p>
<a href="<%= users_path + "/" + u.id.to_s%>">view</a>
</div>
<% end %>
</div>

app/views/users/new.html.erb

<div class="form-div">
<%= form_for @user do |f|%>
   <a class="session-link" href="<%=signin_path%>">Login</a>
<% if @user.errors.any? %> <div id="error_explanation"> <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2> <ul> <% @user.errors.full_messages.each do |msg| %> <li><%= msg %></li> <% end %> </ul> </div> <% end %> 
<label for="name">Username</label>
<%= f.text_field :name%>
<br>
<%= f.submit "Submit"%>
<%end%>
</div>

app/views/users/show.html.erb
<p class="tip">Recipes By <%= @user.name %>
<% @recipes.each do |r|%>
<div class="recipe-container">
<p class="name"><a class="n-link" href="<%= recipes_path + "/" + r.id.to_s%>"><%= r.name %></a></p>
<p>Ingredients: </p>
<div class="ingredients"> <%= simple_format(r.ingredients).html_safe%></div>
<p> How To Video: </p>
<iframe class="embed" src="https://www.youtube.com/embed/<%= get_youtube_id(r.video) %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p>amount: <%= r.amount %></p>
<a class="view-link" href="<%= recipes_path + "/" + r.id.to_s%>">View</a>
</div>
<%end%>